name = "Arya"
uuid = "415bc928-4679-4905-9aff-233f9524af88"
authors = ["Daniel Boyea <aeyobd@gmail.com>"]
version = "0.1.10-DEV-10"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
AccessorsExtra = "33016aad-b69d-45be-9359-82a41f556fd4"
ColorSchemeTools = "d3e213a1-5e82-5c18-bb32-2a58a99f8c46"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataPipes = "02685ad9-2d12-40c3-9f73-c6aeda6a7ff5"
DensityEstimators = "6a64a12f-920b-4cea-9d97-f6c2170ce0ee"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[weakdeps]
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"

[extensions]
AryaMeasurementsExt = "Measurements"

[compat]
Accessors = "0.1.42"
AccessorsExtra = "0.1.98"
DataPipes = "0.3.18"
